//
//  Created by ktiays on 2026/5/28.
//  Copyright (c) 2026 ktiays. All rights reserved.
//

#import "CQFQuartzFilterInputKey.h"

#ifndef __IMPL_CQFFILTER_INPUT_KEY__
#define __IMPL_CQFFILTER_INPUT_KEY__(__NAME, __VAL) CQFQuartzFilterInputKey const CQFQuartzFilterInputKey##__NAME = @#__VAL
#endif

__IMPL_CQFFILTER_INPUT_KEY__(Amount, inputAmount);
__IMPL_CQFFILTER_INPUT_KEY__(BackdropAware, inputBackdropAware);
__IMPL_CQFFILTER_INPUT_KEY__(BleedAmount, inputBleedAmount);
__IMPL_CQFFILTER_INPUT_KEY__(BleedBlurRadius, inputBleedBlurRadius);
__IMPL_CQFFILTER_INPUT_KEY__(BleedColorMatrixBlack, inputBleedColorMatrixBlack);
__IMPL_CQFFILTER_INPUT_KEY__(BleedColorMatrixFillColor, inputBleedColorMatrixFillColor);
__IMPL_CQFFILTER_INPUT_KEY__(BleedColorMatrixSaturation, inputBleedColorMatrixSaturation);
__IMPL_CQFFILTER_INPUT_KEY__(BleedColorMatrixWhite, inputBleedColorMatrixWhite);
__IMPL_CQFFILTER_INPUT_KEY__(BleedDarkenBlend, inputBleedDarkenBlend);
__IMPL_CQFFILTER_INPUT_KEY__(BleedDistance0, inputBleedDistance0);
__IMPL_CQFFILTER_INPUT_KEY__(BleedDistance1, inputBleedDistance1);
__IMPL_CQFFILTER_INPUT_KEY__(BleedHeight, inputBleedHeight);
__IMPL_CQFFILTER_INPUT_KEY__(BleedOpacity, inputBleedOpacity);
__IMPL_CQFFILTER_INPUT_KEY__(BlurDistance0, inputBlurDistance0);
__IMPL_CQFFILTER_INPUT_KEY__(BlurDistance1, inputBlurDistance1);
__IMPL_CQFFILTER_INPUT_KEY__(BlurDistance2, inputBlurDistance2);
__IMPL_CQFFILTER_INPUT_KEY__(BlurDistance3, inputBlurDistance3);
__IMPL_CQFFILTER_INPUT_KEY__(BlurDistance4, inputBlurDistance4);
__IMPL_CQFFILTER_INPUT_KEY__(BlurOpacity0, inputBlurOpacity0);
__IMPL_CQFFILTER_INPUT_KEY__(BlurOpacity1, inputBlurOpacity1);
__IMPL_CQFFILTER_INPUT_KEY__(BlurOpacity2, inputBlurOpacity2);
__IMPL_CQFFILTER_INPUT_KEY__(BlurOpacity3, inputBlurOpacity3);
__IMPL_CQFFILTER_INPUT_KEY__(BlurOpacity4, inputBlurOpacity4);
__IMPL_CQFFILTER_INPUT_KEY__(BlurRadius, inputBlurRadius);
__IMPL_CQFFILTER_INPUT_KEY__(Clamp, inputClamp);
__IMPL_CQFFILTER_INPUT_KEY__(ClampPreserveHue, inputClampPreserveHue);
__IMPL_CQFFILTER_INPUT_KEY__(Color, inputColor);
__IMPL_CQFFILTER_INPUT_KEY__(ColorMap, inputColorMap);
__IMPL_CQFFILTER_INPUT_KEY__(ColorMatrix, inputColorMatrix);
__IMPL_CQFFILTER_INPUT_KEY__(Dither, inputDither);
__IMPL_CQFFILTER_INPUT_KEY__(End, inputEnd);
__IMPL_CQFFILTER_INPUT_KEY__(Fade, inputFade);
__IMPL_CQFFILTER_INPUT_KEY__(FaceColorMatrixBlack, inputFaceColorMatrixBlack);
__IMPL_CQFFILTER_INPUT_KEY__(FaceColorMatrixFillColor, inputFaceColorMatrixFillColor);
__IMPL_CQFFILTER_INPUT_KEY__(FaceColorMatrixSaturation, inputFaceColorMatrixSaturation);
__IMPL_CQFFILTER_INPUT_KEY__(FaceColorMatrixWhite, inputFaceColorMatrixWhite);
__IMPL_CQFFILTER_INPUT_KEY__(FaceOpacity, inputFaceOpacity);
__IMPL_CQFFILTER_INPUT_KEY__(HardEdges, inputHardEdges);
__IMPL_CQFFILTER_INPUT_KEY__(InnerRefractionAmount, inputInnerRefractionAmount);
__IMPL_CQFFILTER_INPUT_KEY__(InnerRefractionHeight, inputInnerRefractionHeight);
__IMPL_CQFFILTER_INPUT_KEY__(MaskImage, inputMaskImage);
__IMPL_CQFFILTER_INPUT_KEY__(MaxHeadroom, inputMaxHeadroom);
__IMPL_CQFFILTER_INPUT_KEY__(NormalizeEdges, inputNormalizeEdges);
__IMPL_CQFFILTER_INPUT_KEY__(OverlayOpacity, inputOverlayOpacity);
__IMPL_CQFFILTER_INPUT_KEY__(OuterRefractionAmount, inputOuterRefractionAmount);
__IMPL_CQFFILTER_INPUT_KEY__(OuterRefractionHeight, inputOuterRefractionHeight);
__IMPL_CQFFILTER_INPUT_KEY__(Quality, inputQuality);
__IMPL_CQFFILTER_INPUT_KEY__(Radius, inputRadius);
__IMPL_CQFFILTER_INPUT_KEY__(RefractionDistance0, inputRefractionDistance0);
__IMPL_CQFFILTER_INPUT_KEY__(RefractionDistance1, inputRefractionDistance1);
__IMPL_CQFFILTER_INPUT_KEY__(RefractionOpacity, inputRefractionOpacity);
__IMPL_CQFFILTER_INPUT_KEY__(SDRGradientDistance0, inputSDRGradientDistance0);
__IMPL_CQFFILTER_INPUT_KEY__(SDRGradientDistance1, inputSDRGradientDistance1);
__IMPL_CQFFILTER_INPUT_KEY__(SDRHoldingToneEnabled, inputSDRHoldingToneEnabled);
__IMPL_CQFFILTER_INPUT_KEY__(SDRHoldingToneWhite, inputSDRHoldingToneWhite);
__IMPL_CQFFILTER_INPUT_KEY__(SDRShadowOpacity, inputSDRShadowOpacity);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowAmount, inputShadowAmount);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowBlurRadius, inputShadowBlurRadius);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowColorMatrixBlack, inputShadowColorMatrixBlack);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowColorMatrixFillColor, inputShadowColorMatrixFillColor);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowColorMatrixSaturation, inputShadowColorMatrixSaturation);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowColorMatrixWhite, inputShadowColorMatrixWhite);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowDistanceOffset, inputShadowDistanceOffset);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowHeight, inputShadowHeight);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowOffset, inputShadowOffset);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowOpacity, inputShadowOpacity);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowRadius, inputShadowRadius);
__IMPL_CQFFILTER_INPUT_KEY__(ShadowVibrancyContribution, inputShadowVibrancyContribution);
__IMPL_CQFFILTER_INPUT_KEY__(SourceSublayerName, inputSourceSublayerName);
__IMPL_CQFFILTER_INPUT_KEY__(Start, inputStart);
__IMPL_CQFFILTER_INPUT_KEY__(Values, inputValues);
