//
//  Created by ktiays on 2026/5/28.
//  Copyright (c) 2026 ktiays. All rights reserved.
//

#ifndef CQFQuartzFilterInputKey_h
#define CQFQuartzFilterInputKey_h

#import <Foundation/Foundation.h>

#ifndef __DEF_CQFFILTER_INPUT_KEY__
#define __DEF_CQFFILTER_INPUT_KEY__(__NAME) FOUNDATION_EXPORT CQFQuartzFilterInputKey const CQFQuartzFilterInputKey##__NAME
#endif

NS_ASSUME_NONNULL_BEGIN

typedef NSString * CQFQuartzFilterInputKey NS_STRING_ENUM NS_SWIFT_NAME(QuartzFilterInputKey);

__DEF_CQFFILTER_INPUT_KEY__(Amount);
__DEF_CQFFILTER_INPUT_KEY__(BackdropAware);
__DEF_CQFFILTER_INPUT_KEY__(BleedAmount);
__DEF_CQFFILTER_INPUT_KEY__(BleedBlurRadius);
__DEF_CQFFILTER_INPUT_KEY__(BleedColorMatrixBlack);
__DEF_CQFFILTER_INPUT_KEY__(BleedColorMatrixFillColor);
__DEF_CQFFILTER_INPUT_KEY__(BleedColorMatrixSaturation);
__DEF_CQFFILTER_INPUT_KEY__(BleedColorMatrixWhite);
__DEF_CQFFILTER_INPUT_KEY__(BleedDarkenBlend);
__DEF_CQFFILTER_INPUT_KEY__(BleedDistance0);
__DEF_CQFFILTER_INPUT_KEY__(BleedDistance1);
__DEF_CQFFILTER_INPUT_KEY__(BleedHeight);
__DEF_CQFFILTER_INPUT_KEY__(BleedOpacity);
__DEF_CQFFILTER_INPUT_KEY__(BlurDistance0);
__DEF_CQFFILTER_INPUT_KEY__(BlurDistance1);
__DEF_CQFFILTER_INPUT_KEY__(BlurDistance2);
__DEF_CQFFILTER_INPUT_KEY__(BlurDistance3);
__DEF_CQFFILTER_INPUT_KEY__(BlurDistance4);
__DEF_CQFFILTER_INPUT_KEY__(BlurOpacity0);
__DEF_CQFFILTER_INPUT_KEY__(BlurOpacity1);
__DEF_CQFFILTER_INPUT_KEY__(BlurOpacity2);
__DEF_CQFFILTER_INPUT_KEY__(BlurOpacity3);
__DEF_CQFFILTER_INPUT_KEY__(BlurOpacity4);
__DEF_CQFFILTER_INPUT_KEY__(BlurRadius);
__DEF_CQFFILTER_INPUT_KEY__(Clamp);
__DEF_CQFFILTER_INPUT_KEY__(ClampPreserveHue);
__DEF_CQFFILTER_INPUT_KEY__(Color);
__DEF_CQFFILTER_INPUT_KEY__(ColorMap);
__DEF_CQFFILTER_INPUT_KEY__(ColorMatrix);
__DEF_CQFFILTER_INPUT_KEY__(Dither);
__DEF_CQFFILTER_INPUT_KEY__(Fade);
__DEF_CQFFILTER_INPUT_KEY__(FaceColorMatrixBlack);
__DEF_CQFFILTER_INPUT_KEY__(FaceColorMatrixFillColor);
__DEF_CQFFILTER_INPUT_KEY__(FaceColorMatrixSaturation);
__DEF_CQFFILTER_INPUT_KEY__(FaceColorMatrixWhite);
__DEF_CQFFILTER_INPUT_KEY__(FaceOpacity);
__DEF_CQFFILTER_INPUT_KEY__(HardEdges);
__DEF_CQFFILTER_INPUT_KEY__(InnerRefractionAmount);
__DEF_CQFFILTER_INPUT_KEY__(InnerRefractionHeight);
__DEF_CQFFILTER_INPUT_KEY__(MaskImage);
__DEF_CQFFILTER_INPUT_KEY__(MaxHeadroom);
__DEF_CQFFILTER_INPUT_KEY__(NormalizeEdges);
__DEF_CQFFILTER_INPUT_KEY__(OverlayOpacity);
__DEF_CQFFILTER_INPUT_KEY__(OuterRefractionAmount);
__DEF_CQFFILTER_INPUT_KEY__(OuterRefractionHeight);
__DEF_CQFFILTER_INPUT_KEY__(Quality);
__DEF_CQFFILTER_INPUT_KEY__(Radius);
__DEF_CQFFILTER_INPUT_KEY__(RefractionDistance0);
__DEF_CQFFILTER_INPUT_KEY__(RefractionDistance1);
__DEF_CQFFILTER_INPUT_KEY__(RefractionOpacity);
__DEF_CQFFILTER_INPUT_KEY__(SDRGradientDistance0);
__DEF_CQFFILTER_INPUT_KEY__(SDRGradientDistance1);
__DEF_CQFFILTER_INPUT_KEY__(SDRHoldingToneEnabled);
__DEF_CQFFILTER_INPUT_KEY__(SDRHoldingToneWhite);
__DEF_CQFFILTER_INPUT_KEY__(SDRShadowOpacity);
__DEF_CQFFILTER_INPUT_KEY__(ShadowAmount);
__DEF_CQFFILTER_INPUT_KEY__(ShadowBlurRadius);
__DEF_CQFFILTER_INPUT_KEY__(ShadowColorMatrixBlack);
__DEF_CQFFILTER_INPUT_KEY__(ShadowColorMatrixFillColor);
__DEF_CQFFILTER_INPUT_KEY__(ShadowColorMatrixSaturation);
__DEF_CQFFILTER_INPUT_KEY__(ShadowColorMatrixWhite);
__DEF_CQFFILTER_INPUT_KEY__(ShadowDistanceOffset);
__DEF_CQFFILTER_INPUT_KEY__(ShadowHeight);
__DEF_CQFFILTER_INPUT_KEY__(ShadowOffset);
__DEF_CQFFILTER_INPUT_KEY__(ShadowOpacity);
__DEF_CQFFILTER_INPUT_KEY__(ShadowRadius);
__DEF_CQFFILTER_INPUT_KEY__(ShadowVibrancyContribution);
__DEF_CQFFILTER_INPUT_KEY__(SourceSublayerName);
__DEF_CQFFILTER_INPUT_KEY__(Values);

NS_ASSUME_NONNULL_END

#endif /* CQFQuartzFilterInputKey_h */
